//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.CasoLibros.wsLibros {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsLibros.wsLibrosSoap")]
    public interface wsLibrosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje ListarLibrosRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarLibros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Presentacion.CasoLibros.wsLibros.ListarLibrosResponse ListarLibros(Presentacion.CasoLibros.wsLibros.ListarLibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarLibros", ReplyAction="*")]
        System.Threading.Tasks.Task<Presentacion.CasoLibros.wsLibros.ListarLibrosResponse> ListarLibrosAsync(Presentacion.CasoLibros.wsLibros.ListarLibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarLibro(int Codigo_Libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultarLibroAsync(int Codigo_Libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EliminarLibro(int CODIGO_PRODUCTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarLibroAsync(int CODIGO_PRODUCTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertarLibro(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task InsertarLibroAsync(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ActualizarLibro(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task ActualizarLibroAsync(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessKey {
            get {
                return this.accessKeyField;
            }
            set {
                this.accessKeyField = value;
                this.RaisePropertyChanged("AccessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarLibros", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarLibrosRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Presentacion.CasoLibros.wsLibros.UserDetails UserDetails;
        
        public ListarLibrosRequest() {
        }
        
        public ListarLibrosRequest(Presentacion.CasoLibros.wsLibros.UserDetails UserDetails) {
            this.UserDetails = UserDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarLibrosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataSet ListarLibrosResult;
        
        public ListarLibrosResponse() {
        }
        
        public ListarLibrosResponse(System.Data.DataSet ListarLibrosResult) {
            this.ListarLibrosResult = ListarLibrosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsLibrosSoapChannel : Presentacion.CasoLibros.wsLibros.wsLibrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsLibrosSoapClient : System.ServiceModel.ClientBase<Presentacion.CasoLibros.wsLibros.wsLibrosSoap>, Presentacion.CasoLibros.wsLibros.wsLibrosSoap {
        
        public wsLibrosSoapClient() {
        }
        
        public wsLibrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsLibrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLibrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLibrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presentacion.CasoLibros.wsLibros.ListarLibrosResponse Presentacion.CasoLibros.wsLibros.wsLibrosSoap.ListarLibros(Presentacion.CasoLibros.wsLibros.ListarLibrosRequest request) {
            return base.Channel.ListarLibros(request);
        }
        
        public System.Data.DataSet ListarLibros(Presentacion.CasoLibros.wsLibros.UserDetails UserDetails) {
            Presentacion.CasoLibros.wsLibros.ListarLibrosRequest inValue = new Presentacion.CasoLibros.wsLibros.ListarLibrosRequest();
            inValue.UserDetails = UserDetails;
            Presentacion.CasoLibros.wsLibros.ListarLibrosResponse retVal = ((Presentacion.CasoLibros.wsLibros.wsLibrosSoap)(this)).ListarLibros(inValue);
            return retVal.ListarLibrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Presentacion.CasoLibros.wsLibros.ListarLibrosResponse> Presentacion.CasoLibros.wsLibros.wsLibrosSoap.ListarLibrosAsync(Presentacion.CasoLibros.wsLibros.ListarLibrosRequest request) {
            return base.Channel.ListarLibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Presentacion.CasoLibros.wsLibros.ListarLibrosResponse> ListarLibrosAsync(Presentacion.CasoLibros.wsLibros.UserDetails UserDetails) {
            Presentacion.CasoLibros.wsLibros.ListarLibrosRequest inValue = new Presentacion.CasoLibros.wsLibros.ListarLibrosRequest();
            inValue.UserDetails = UserDetails;
            return ((Presentacion.CasoLibros.wsLibros.wsLibrosSoap)(this)).ListarLibrosAsync(inValue);
        }
        
        public System.Data.DataSet ConsultarLibro(int Codigo_Libro) {
            return base.Channel.ConsultarLibro(Codigo_Libro);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultarLibroAsync(int Codigo_Libro) {
            return base.Channel.ConsultarLibroAsync(Codigo_Libro);
        }
        
        public void EliminarLibro(int CODIGO_PRODUCTO) {
            base.Channel.EliminarLibro(CODIGO_PRODUCTO);
        }
        
        public System.Threading.Tasks.Task EliminarLibroAsync(int CODIGO_PRODUCTO) {
            return base.Channel.EliminarLibroAsync(CODIGO_PRODUCTO);
        }
        
        public void InsertarLibro(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION) {
            base.Channel.InsertarLibro(CODIGO_PRODUCTO, NOMBRE_PRODUCTO, IMAGEN_PRODUCTO, DESCRIPCION);
        }
        
        public System.Threading.Tasks.Task InsertarLibroAsync(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION) {
            return base.Channel.InsertarLibroAsync(CODIGO_PRODUCTO, NOMBRE_PRODUCTO, IMAGEN_PRODUCTO, DESCRIPCION);
        }
        
        public void ActualizarLibro(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION) {
            base.Channel.ActualizarLibro(CODIGO_PRODUCTO, NOMBRE_PRODUCTO, IMAGEN_PRODUCTO, DESCRIPCION);
        }
        
        public System.Threading.Tasks.Task ActualizarLibroAsync(int CODIGO_PRODUCTO, string NOMBRE_PRODUCTO, string IMAGEN_PRODUCTO, string DESCRIPCION) {
            return base.Channel.ActualizarLibroAsync(CODIGO_PRODUCTO, NOMBRE_PRODUCTO, IMAGEN_PRODUCTO, DESCRIPCION);
        }
    }
}
