//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.CasoLibros.wsLibros {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsLibros.WsLibrosSoap")]
    public interface WsLibrosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertarLibro(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task InsertarLibroAsync(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ActualizarLibro(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task ActualizarLibroAsync(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarLibros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarLibros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarLibros", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarLibrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ConsultarLibro(int codigoLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ConsultarLibroAsync(int codigoLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarLibro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EliminarLibro(int codigoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarLibroAsync(int codigoProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsLibrosSoapChannel : Presentacion.CasoLibros.wsLibros.WsLibrosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsLibrosSoapClient : System.ServiceModel.ClientBase<Presentacion.CasoLibros.wsLibros.WsLibrosSoap>, Presentacion.CasoLibros.wsLibros.WsLibrosSoap {
        
        public WsLibrosSoapClient() {
        }
        
        public WsLibrosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsLibrosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsLibrosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsLibrosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertarLibro(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion) {
            base.Channel.InsertarLibro(codigoProducto, nombreProducto, imagenProducto, descripcion);
        }
        
        public System.Threading.Tasks.Task InsertarLibroAsync(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion) {
            return base.Channel.InsertarLibroAsync(codigoProducto, nombreProducto, imagenProducto, descripcion);
        }
        
        public void ActualizarLibro(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion) {
            base.Channel.ActualizarLibro(codigoProducto, nombreProducto, imagenProducto, descripcion);
        }
        
        public System.Threading.Tasks.Task ActualizarLibroAsync(int codigoProducto, string nombreProducto, string imagenProducto, string descripcion) {
            return base.Channel.ActualizarLibroAsync(codigoProducto, nombreProducto, imagenProducto, descripcion);
        }
        
        public System.Data.DataSet ListarLibros() {
            return base.Channel.ListarLibros();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarLibrosAsync() {
            return base.Channel.ListarLibrosAsync();
        }
        
        public System.Data.DataSet ConsultarLibro(int codigoLibro) {
            return base.Channel.ConsultarLibro(codigoLibro);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ConsultarLibroAsync(int codigoLibro) {
            return base.Channel.ConsultarLibroAsync(codigoLibro);
        }
        
        public void EliminarLibro(int codigoProducto) {
            base.Channel.EliminarLibro(codigoProducto);
        }
        
        public System.Threading.Tasks.Task EliminarLibroAsync(int codigoProducto) {
            return base.Channel.EliminarLibroAsync(codigoProducto);
        }
    }
}
