USE [LibreriaVirtual]
GO

/****** Object:  Table [dbo].[PRODUCTOS]    Script Date: 10-05-2021 15:47:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTOS](
	[ID_PRODUCTO] [int] NOT NULL,
	[CODIGO_PRODUCTO] [nchar](10) NULL,
	[NOMBRE_PRODUCTO] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


